copyright = "Copyright © 2020-{year} Chris Halstead. All Rights Reserved."
rssLimit = 100
timeZone = "America/Los_Angeles"

[mediaTypes]
  [mediaTypes."application/atom+xml"]
    suffixes = ["xml"]

[outputs]
  home = ["ATOM", "HTML", "JSON"]
  page = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats]
  [outputFormats.ATOM]
    mediaType = "application/atom+xml"
    baseName  = "feed"
