dateFormatAtomFeed = "2006-01-02T15:04:05-07:00"
dateFormatTag = "2006"
feedUUID = "14c05062-1acc-41a1-948f-5893adf227a3"
icon = "https://images.c20d.us/cards/feature-square.jpg"
icon96 = "https://images.c20d.us/site-img/profile-96x96.jpg"
logo = "https://images.c20d.us/site-img/round-logo.png"
mainSections = ["posts"]
